image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/debian:stable-slim

stages:
  - test
  - build
  - review
  - release
  - publish

.rules:
  rules:
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_TAG || $CI_COMMIT_BRANCH'

include:
  - local: "/.gitlab-ci/jobs/build.yml"
  - local: "/.gitlab-ci/jobs/test.yml"
  - local: "/.gitlab-ci/jobs/review.yml"
  - local: "/.gitlab-ci/jobs/publish.yml"
  - local: ".gitlab-ci/jobs/release.yml"